# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [King, Covid]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username hunterz.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username KIK
issuehunt: # Replace with a single IssueHunt username Opera
otechie: # Replace with a single Otechie username HANNA
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Https://icann.org','ttps://ro.co','https://www.kraken.com/en-us/security/bug-bounty','https://podcasts.apple.com/us/podcast/overheard-at-national-geographic/id1466697207?i=1000472896229','https://voodoo.io','https://'https://cashapp.com','https://knightlinelegal.com','https://'https://mypillow.com','https://Marchofdimes.org'https://tictok.com','https://ultra.com','https://tjhlaw.com']
